on: push
name: Run Tests
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:14

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run tests
        run: |
          npm ci
          npm run test